# Generated by Django 2.2.2 on 2019-07-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
