# Generated by Django 2.2.2 on 2019-07-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=30)),
                ('C_Class', models.CharField(max_length=10)),
                ('C_Age', models.IntegerField()),
                ('C_Addr', models.TextField(max_length=100)),
            ],
        ),
    ]
