# Generated by Django 2.2.2 on 2019-07-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
    ]
