# Generated by Django 2.2.2 on 2019-07-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190706_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_Author',
            new_name='BookAuthor',
        ),
        migrations.RenameModel(
            old_name='Book_Publisher',
            new_name='BookPublisher',
        ),
    ]
