# Generated by Django 2.2.2 on 2019-07-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190706_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookPublisher',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
